# Generated by Django 2.2.5 on 2020-07-30 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类别名')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='试卷名')),
                ('introduce', models.CharField(max_length=256, verbose_name='试卷介绍')),
                ('max_time', models.IntegerField(verbose_name='最大时长')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0, verbose_name='总分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='试题题目')),
                ('grade', models.IntegerField(default=0, verbose_name='分数')),
                ('types', models.CharField(max_length=30, verbose_name='题目类型')),
                ('answer', models.CharField(max_length=256, verbose_name='答案')),
                ('options', models.CharField(max_length=256, null=True, verbose_name='选项')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_key', to='organization.Message')),
            ],
        ),
    ]
