# Generated by Django 2.0.5 on 2020-07-30 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='an_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_key', to='organization.Classify'),
        ),
        migrations.AddField(
            model_name='message',
            name='up_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
