# Generated by Django 2.2.5 on 2020-07-28 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='an_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Classify'),
        ),
        migrations.AddField(
            model_name='message',
            name='up_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
